# -*- coding: utf-8 -*-
"""OverHead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198-36q6Z_ViINY0tcu9hlGX8jFoBR7rK

Descrição: Sistema para comparação entre dados da tabela final e tabela de overhead

OBS: Para rodar, copiar arquivo para "Meu Drive" ou mudar diretório no código

## Preparando Ambiente

### Instalar bibliotecas
"""

from google.colab import drive;
from openpyxl import Workbook,load_workbook;
import pandas as pd
import numpy as np
import openpyxl
import os

# Conectar ao Drive
drive.mount('/media/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# Definindo Workplace
# %cd '/media/gdrive/MyDrive'

"""## Totalização Overhead

#### Totaliza Arquivo Overhead por Mês/Ano


"""

# Commented out IPython magic to ensure Python compatibility.
# %cd '/media/gdrive/MyDrive/Overhead'

# Carregue o arquivo Excel
excel_file = 'RAP - Fundo 8329 - 01-01-2020 à 11-10-2023.xlsx'
df = pd.read_excel(excel_file, skiprows=5)  # Começa na 6ª linha (índice 5)

# Crie um DataFrame vazio para armazenar os totais
df_total = pd.DataFrame(columns=['Mês/Ano', 'Total'])

# Loop para todas as linhas do arquivo
for index, row in df.iterrows():
    date = row[1]  # Nesse arquivo, as datas estão na coluna "B"
    value = row[5]  # Nesse arquivo, os valores estão na coluna "E"

    month_year = date.strftime('%b/%Y')  # Formate a data como "Mês/Ano"

    # Verifica se o mês/ano já existe no DataFrame de totais
    if month_year in df_total['Mês/Ano'].values:
        # Se já existe, adiciona o valor ao total existente
        df_total.loc[df_total['Mês/Ano'] == month_year, 'Total'] += value
    else:
        # Caso contrário, cria uma nova entrada no DataFrame de totais
        df_total = df_total.append({'Mês/Ano': month_year, 'Total': value}, ignore_index=True)

# Salva o DataFrame de totais em uma nova planilha no mesmo arquivo
with pd.ExcelWriter(excel_file, engine='openpyxl', mode='a') as writer:
    df_total.to_excel(writer, sheet_name='Total', index=False)

print("Totais calculados e salvos na planilha 'Total'")